# Example:
#   kubectl create secret generic mssql-login \
#     --namespace team-b \
#     --from-literal=MSSQL_SA_PASSWORD="$(openssl rand -base64 24)"
---
apiVersion: v1
kind: Secret
metadata:
  name: mssql-login
type: Opaque
data:
  MSSQL_SA_PASSWORD: "<BASE64_ENCODED_PASSWORD_HERE>"
