---
apiVersion: v1
kind: Service
metadata:
  name: hello
  annotations:
    omni-kube-service-exposer.sidero.dev/label: Team-B
    omni-kube-service-exposer.sidero.dev/prefix: teamb
    omni-kube-service-exposer.sidero.dev/port: '8080'
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 8080
