---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: team-a-admin
  namespace: team-a
  labels:
    app.kubernetes.io/managed-by: tenant-baseline
    tenant: team-a
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
