---
cert-manager:
  crds:
    keep: true

  replicaCount: 3

  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi

  dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53"
  dns01RecursiveNameserversOnly: true

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

  webhook:
    replicaCount: 3

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi

    networkPolicy:
      enabled: true

  cainjector:
    replicaCount: 2

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi
