---
# Example SSO configuration for GitHub
# IMPORTANT: Store clientSecret in Vault, not in this file!
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # ArgoCD server URL (update with your actual URL)
  url: https://argocd.lab.mxe11.nl

  # Resource tracking method
  application.resourceTrackingMethod: annotation

  # OIDC configuration for GitHub
  # Prerequisites:
  # 1. Create GitHub OAuth App: https://github.com/settings/developers
  # 2. Set Authorization callback URL: https://argocd.lab.mxe11.nl/auth/callback
  # 3. Store clientID and clientSecret in Vault
  oidc.config: |
    name: GitHub
    issuer: https://token.actions.githubusercontent.com
    clientID: $oidc.github.clientId
    clientSecret: $oidc.github.clientSecret
    requestedScopes:
      - openid
      - profile
      - email
    requestedIDTokenClaims:
      groups:
        essential: true

  # Disable Dex (using external OIDC)
  dex.config: ""

  # Admin enabled
  admin.enabled: "true"

  # Timeout settings
  timeout.reconciliation: 180s
  timeout.hard.reconciliation: 0s

---
# External Secret to fetch GitHub OAuth credentials from Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-github
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster-store
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: oidc.github.clientId
      remoteRef:
        key: argocd/oidc-github
        property: clientId
    - secretKey: oidc.github.clientSecret
      remoteRef:
        key: argocd/oidc-github
        property: clientSecret
