---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  # Policy CSV format: p, subject, resource, action, object, effect
  # Group mapping format: g, subject, inherited
  policy.csv: |
    # ============================================
    # Platform Admin - Full Access
    # ============================================
    g, platform-admins, role:admin

    # ============================================
    # Team A Permissions
    # ============================================
    # Map groups to custom roles
    g, team-a-admins, role:team-a-admin
    g, team-a-developers, role:team-a-developer
    g, team-a-viewers, role:team-a-viewer

    # Team A Admin role
    p, role:team-a-admin, applications, *, team-a/*, allow
    p, role:team-a-admin, repositories, get, *, allow
    p, role:team-a-admin, repositories, create, *, allow
    p, role:team-a-admin, projects, get, team-a, allow
    p, role:team-a-admin, logs, get, team-a/*, allow
    p, role:team-a-admin, exec, create, team-a/*, allow

    # Team A Developer role
    p, role:team-a-developer, applications, get, team-a/*, allow
    p, role:team-a-developer, applications, sync, team-a/*, allow
    p, role:team-a-developer, applications, override, team-a/*, allow
    p, role:team-a-developer, repositories, get, *, allow
    p, role:team-a-developer, projects, get, team-a, allow
    p, role:team-a-developer, logs, get, team-a/*, allow

    # Team A Viewer role
    p, role:team-a-viewer, applications, get, team-a/*, allow
    p, role:team-a-viewer, projects, get, team-a, allow
    p, role:team-a-viewer, logs, get, team-a/*, allow

    # ============================================
    # Team B Permissions
    # ============================================
    g, team-b-admins, role:team-b-admin
    g, team-b-developers, role:team-b-developer
    g, team-b-viewers, role:team-b-viewer

    # Team B Admin role
    p, role:team-b-admin, applications, *, team-b/*, allow
    p, role:team-b-admin, repositories, get, *, allow
    p, role:team-b-admin, repositories, create, *, allow
    p, role:team-b-admin, projects, get, team-b, allow
    p, role:team-b-admin, logs, get, team-b/*, allow
    p, role:team-b-admin, exec, create, team-b/*, allow

    # Team B Developer role
    p, role:team-b-developer, applications, get, team-b/*, allow
    p, role:team-b-developer, applications, sync, team-b/*, allow
    p, role:team-b-developer, applications, override, team-b/*, allow
    p, role:team-b-developer, repositories, get, *, allow
    p, role:team-b-developer, projects, get, team-b, allow
    p, role:team-b-developer, logs, get, team-b/*, allow

    # Team B Viewer role
    p, role:team-b-viewer, applications, get, team-b/*, allow
    p, role:team-b-viewer, projects, get, team-b, allow
    p, role:team-b-viewer, logs, get, team-b/*, allow

  # Default role for authenticated users (very restrictive)
  policy.default: role:readonly

  # Enable OIDC group claims
  scopes: '[groups, email]'

  # Optional: Policy matching mode (glob or regex)
  policy.matchMode: 'glob'
