---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster-store
  target:
    name: argocd-secret
    creationPolicy: Owner
  data:
    - secretKey: server.secretkey
      remoteRef:
        key: argocd/admin
        property: server.secretkey
    - secretKey: admin.password
      remoteRef:
        key: argocd/admin
        property: admin.password
    - secretKey: admin.passwordMtime
      remoteRef:
        key: argocd/admin
        property: admin.passwordMtime
