---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.lab.mxe11.nl
  application.resourceTrackingMethod: annotation

  # GitHub SSO Configuration
  # Prerequisites:
  # 1. Create GitHub OAuth App: https://github.com/settings/developers
  # 2. Set Authorization callback URL: https://argocd.lab.mxe11.nl/auth/callback
  # 3. Store clientID and clientSecret in Vault at: kv/argocd/oidc-github
  oidc.config: |
    name: GitHub
    issuer: https://token.actions.githubusercontent.com
    clientID: $oidc.github.clientId
    clientSecret: $oidc.github.clientSecret
    requestedScopes:
      - openid
      - profile
      - email
    requestedIDTokenClaims:
      groups:
        essential: true

  # Disable Dex (using external OIDC)
  dex.config: ""

  # Keep admin account enabled for emergency access
  admin.enabled: "true"
