---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  # Use Omni Workload Proxying HTTP-only
  server.insecure: 'true'
  # Allow embedding in iframes for Omni
  server.x.frame.options: ''
