---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    # ============================================
    # ArgoCD RBAC - Admin Only (No SSO)
    # ============================================
    # Admin user has full access via local account
    # Tenant users access Kubernetes directly via Omni + RBAC
    # (see tenants/team-*/resources/*-rolebinding.yaml)

  # Default role for authenticated users (admin only)
  policy.default: role:readonly
