---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  # ArgoCD server secret key - generate with: openssl rand -base64 32
  server.secretkey: "CHANGEME-generate-with-openssl-rand-base64-32"
  # ArgoCD admin password (bcrypt hash) - generate with: argocd account bcrypt --password <password>
  admin.password: "CHANGEME-bcrypt-hash-of-admin-password"
  # Password modification time in RFC3339 format
  admin.passwordMtime: "2025-10-21T00:00:00Z"
