# apps/argocd/argocd/vault-secretstore.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-argocd
  namespace: argocd
spec:
  controllerServiceAccountRef:
    name: external-secrets
    namespace: external-secrets
  provider:
    vault:
      server: https://vault.vault.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: argocd-external-secrets
