---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: team-b-admin
  namespace: team-b
  labels:
    app.kubernetes.io/managed-by: tenant-baseline
    tenant: team-b
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
