---
vault:
  server:
    ha:
      enabled: true
      raft:
        enabled: true
        setNodeId: true
        config: |
          cluster_name = "vault-integrated-storage"
          storage "raft" {
            path = "/vault/data/"
          }
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_disable = "true"
          }
          service_registration "kubernetes" {}
      replicas: 3
    serviceAccount:
      create: true
  ui:
    enabled: true
    annotations:
      omni-kube-service-exposer.sidero.dev/port: '8200'
      omni-kube-service-exposer.sidero.dev/label: Vault
