---
vault:
  global:
    tlsDisable: true
  injector:
    enabled: false
  csi:
    enabled: false
  server:
    ha:
      enabled: false
    standalone:
      enabled: true
    dataStorage:
      enabled: true
      size: 10Gi
    service:
      type: ClusterIP
      port: 8200
      annotations:
        omni-kube-service-exposer.sidero.dev/label: Vault
        omni-kube-service-exposer.sidero.dev/prefix: vault
        omni-kube-service-exposer.sidero.dev/port: '8200'
  ui:
    enabled: true
