---
vault:
  server:
    ha:
      enabled: true
      raft:
        enabled: true
        setNodeId: true
        config: |
          cluster_name = "vault-integrated-storage"
          storage "raft" {
            path = "/vault/data/"
          }
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_disable = "true"
          }
          service_registration "kubernetes" {}
    service:
      type: ClusterIP
      port: 8200
      annotations:
        omni-kube-service-exposer.sidero.dev/label: "Vault"
        omni-kube-service-exposer.sidero.dev/port: '8200'
    serviceAccount:
      create: true
      name: vault
  ui:
    enabled: true
