external-secrets:
  installCRDs: true
  crds:
    createClusterExternalSecret: true
    createClusterSecretStore: true
    createClusterGenerator: true
    createClusterPushSecret: true
    createPushSecret: true
  replicaCount: 1
  # Create namespace for external-secrets
  createNamespace: false
  # Webhook configuration
  webhook:
    port: 9443
