---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-app-secret
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-dev
    kind: SecretStore
  target:
    name: demo-app-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: app/demo
        property: username
    - secretKey: password
      remoteRef:
        key: app/demo
        property: password
