---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
type: Opaque
stringData:
  token: "root"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-dev
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault-dev.vault.svc:8200"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
