apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.31.0
    helm:
      values: |
        global:
          enabled: true
        ui:
          enabled: true
          serviceType: ClusterIP
          annotations:
            omni-kube-service-exposer.sidero.dev/port: '8200'
            omni-kube-service-exposer.sidero.dev/label: Vault Dev
            omni-kube-service-exposer.sidero.dev/alias: vault-dev
        server:
          dev:
            enabled: true
          logLevel: "info"
        injector:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
  ignoreDifferences:
    - kind: MutatingWebhookConfiguration
      group: admissionregistration.k8s.io
      namespace: default
      jqPathExpressions:
        - '.webhooks[] | select(.name == "vault-injector-webhook.external-secrets.svc") | .clientConfig.caBundle'
