name: check-dirty
on:
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Setup TF docs
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: terraform-docs/terraform-docs
      - name: dirty-check
        run: |
          make check-dirty
