---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-vault-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/matjahs/omni-cluster-1.git
    targetRevision: main
    path: apps/eso-vault-demo/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
